from watchlist_app.views.watch_list_api_view import WatchListView
from watchlist_app.views.watch_list_api_view import WatchDetailView
from watchlist_app.views.stream_platform_api_view import StreamPlatformListView
from watchlist_app.views.stream_platform_api_view import StreamPlatformDetailView
