from watchlist_app.views.watch_list_api_view import WatchListView
from watchlist_app.views.watch_list_api_view import WatchDetailView
from watchlist_app.views.stream_platform_api_view import StreamPlatformListView
from watchlist_app.views.stream_platform_api_view import StreamPlatformDetailView
from watchlist_app.views.reviews_generic_apiview import ReviewListView
from watchlist_app.views.reviews_generic_apiview import ReviewDetailView
from watchlist_app.views.reviews_generic_apiview import ReviewList
from watchlist_app.views.reviews_generic_apiview import ReviewCreateView